name: Node.js CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]
    env:
      NEXT_URL: ${{secrets.NEXT_URL}}
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
      ENCRYPTION_KEY: ${{secrets.ENCRYPTION_KEY}}
      UPLOADTHING_TOKEN: ${{secrets.UPLOADTHING_TOKEN}}
      UPLOADTHING_SECRET: ${{secrets.UPLOADTHING_SECRET}}
      RESEND_API_KEY: ${{secrets.RESEND_API_KEY}}
      GITHUB_CLIENT_ID: ${{secrets.GITHUB_CLIENT_ID}}
      GITHUB_CLIENT_SECRET: ${{secrets.GITHUB_CLIENT_SECRET}}
      GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
      GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
      UPLOADTHING_APPID: ${{secrets.UPLOADTHING_APPID}}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
